### ISSUE TITLE
Deep Schema Test

### ISSUE THREAD

**Issue by alanjames1987** [molnarg/js-schema#21]
The following validates as `false`, but should evaluate to `true` because the object being validated is the exact same as the schema created.

```js
var schemaTester = schema({
	project_users: [{
		id: '5'
	}]
});

var valid = schemaTester({
	project_users: [{
		id: '5'
	}]
});

console.log(valid); // false but should be true
```

**Comment by arian-hosseinzadeh** [comment]
Any solution for this problem ?

**Comment by molnarg** [comment]
Can anyone cite a use case for this 'exact match' rule? I'm considering removing this from js-schema, and using the syntax for something else, such as the array extension, which is now Array.of, but that conflicts with an ES6 API. (#32)

**Comment by molnarg** [comment]
Sorry, I was not right when I acknowledged that this is a bug. In fact, according to the rules, this should be (and is) valid: `{ project_users: {id:'5'} }` (without the array)

**Comment by molnarg** [comment]
I'm still curious of any use cases for the deep equality test

**Comment by alanjames1987** [comment]
The example I posted to start this issue is a real world use case. Aside from that I don't have any other use cases so far.

**Comment by molnarg** [comment]
Another way to do something like this without explicit support is { id: '5', '*': null } which should be fine in most cases.
