### ISSUE TITLE
not present optional fields are reported as errors

### ISSUE THREAD

**Issue by piebe** [molnarg/js-schema#27]
var testSchema = schema({
					'?optional': String
				});

  // validating should show the schema to be valid, this works
  expect(testSchema({})).toBeTruthy();

  // checking for errors should return false, but instead returns { optional : 'undefined is not a String' }
  expect(testSchema.errors({})).toEqual(false);

**Comment by molnarg** [comment]
Thanks for reporting, I've just pushed the fix.
