### ISSUE TITLE
Multiple Datatype Checking

### ISSUE THREAD

**Issue by alanjames1987** [molnarg/js-schema#28]
It would be great to be able to check if a property of an object is one data type or another. 

For example I would like to be able to check if something is a number between a certain range or just null.

**Comment by molnarg** [comment]
You mean something like this: `[Number.min(1).max(5), null]`, but with the ability to determine which one was matched?

**Comment by alanjames1987** [comment]
Yes. I discovered that shortly after posting this issue. That solved the problem perfectly. I must have forgotten to comment and close.

Thank you.
