### ISSUE TITLE
issues running bower install js-schema

### ISSUE THREAD

**Issue by ORESoftware** [molnarg/js-schema#29]
Just want to let you know I got some mixed messages when installing js-schema with bower. See console output here:

![image](https://cloud.githubusercontent.com/assets/11139560/6683100/b330eedc-cc3e-11e4-98d6-9acb8dbb1b1e.png)

**Comment by molnarg** [comment]
Thanks, I believe it is fixed now. The only problem was the mismatch between package.json and bower.json.

**Comment by ORESoftware** [comment]
cool thanks, will let you know if it works
