### ISSUE TITLE
Add ability to generate base instance from schema

### ISSUE THREAD

**Issue by bcherny** [molnarg/js-schema#31]
```js
let foo = schema({
  foo: String,
  bar: Boolean,
  baz: Array.of(Number),
})

foo.generate()
// => {
//   foo: '',
//   bar: false,
//   baz: []
//
```

This is useful when using js-schema to back models. With this generate extension, it can be used to both validate the model and generate scaffolding to populate the model. The latter is useful for a case like:

```js
class Foo {
  constructor (data) {
    _.assign(this, this.schema, data)
  }

  schema: schema({
    foo: String,
    bar: Number,
    baz: Function
  })
}

new Foo ({ foo: 'bar' })
// => {
//   foo: 'bar',
//   bar: 0,
//   baz: Noop
// }
```

**Comment by bcherny** [comment]
The code for this is pretty simple:

```js
function getDefault (type, min, max) {
  let defaults = {
    array: [],
    boolean: false,
    number: min > 0 ? min : 0,
    string: ''
  }
  return defaults[type]
}

function base (schema) {
  if (schema.properties) {
    return Object
      .keys(schema.properties, base)
      .map(_ => base(schema.properties[_]))
  }
  return getDefault(schema.type, schema.minimum, schema.maximum)
}
```

@molnarg lmk if you like this proposal, and I can turn this into a PR.

**Comment by molnarg** [comment]
It would be possible to have something like you describe in js-schema, but I believe that it would come with more maintenance burden than the value it has for most of the users of js-schema.

js-schema used to have a method for generating random models based on schema. In the end, I've decided to move it out of the js-schema project to keep the core simpler, and moved it to a separate project: https://github.com/molnarg/generate.js You could look at this library and implement something you describe like I did in generate.js!

**Comment by bcherny** [comment]
I did implement it in my own codebase, but it would be pretty cool to be able to generate base (non-random) data with js-schema core.

Maybe if there's more interest from the community we can revisit.
