### ISSUE TITLE
When calling #toJSON on a schema, "Function" is capitalized but other types are not

### ISSUE THREAD

**Issue by bcherny** [molnarg/js-schema#34]

**Comment by molnarg** [comment]
Can you please provide and example?

**Comment by bcherny** [comment]
Ah, this is actually an issue with my fork of js-schema, not js-schema core :)

There is, however, a different issue with js-schema:

```js
> let mySchema = schema({
  foo: String,
  bar: Function
})
> mySchema.toJSON()
Object {
  properties: Object {
    bar: Object {
      required: true
    }
    foo: Object {
      required: true
      type: "string"
    }
  }
  type: "object"
}
```

note that a param of type `function` is missing a `type` when #toJSON'd.

**Comment by molnarg** [comment]
Yeah, I know about this. The reason is that JSON Schema spec does not support function as type. Closing this, and continuing discussion in the other open issues related to this.
