### ISSUE TITLE
property descriptions

### ISSUE THREAD

**Issue by acthp** [molnarg/js-schema#36]
Is there a way to add property descriptions?

**Comment by molnarg** [comment]
What do you mean by property descriptions? A comment associated with a property?

**Comment by acthp** [comment]
Right.. I found the undocumented 'foo : bar' syntax that populates the 'title' for a property. But I believe there's also 'description' for a property. If I create a sub-schema, I can pass it in as the first param to schema(), but haven't found a way of doing it inline.

**Comment by molnarg** [comment]
Yes, that's all you can do, 1. the undocumented syntax and 2. first param of schema, but no way to do it inline. There is no intuitive syntax for this in the inline case that I can think of...

**Comment by molnarg** [comment]
I will close this for now, since it is technically possible, just not the easy way. Feel free to propose an intuitive syntax for this, and if we can come up with something reasonably good, it might be included in the lib.
